{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iac-operator.fullname" . }}-webhook-service
  labels:
    {{- include "iac-operator.labels" . | nindent 4 }}
  {{- with .Values.webhook.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.webhook.service.type }}
  ports:
  - name: webhook
    port: 443
    targetPort: webhook
    protocol: TCP
  selector:
    control-plane: controller-manager
    {{- include "iac-operator.selectorLabels" . | nindent 4 }}
{{- end }}