kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "facets-notification-crb"
  labels:
    {{- include "facets-notification-controller.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: "facets-notification-sa"
  namespace: default
roleRef:
  kind: ClusterRole
  name: "facets-notification-cr"
  apiGroup: rbac.authorization.k8s.io
