kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "facets-notification-cr"
  labels:
    {{- include "facets-notification-controller.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "patch", "annotate"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
