apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "facets-notification-controller.fullname" . }}-pr
  labels:
  {{- include "facets-notification-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "facets-notification-controller.fullname" . }}-prb
  labels:
  {{- include "facets-notification-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "facets-notification-controller.fullname" . }}-pr'
subjects:
- kind: ServiceAccount
  name: '{{ include "facets-notification-controller.fullname" . }}'
  namespace: '{{ .Release.Namespace }}'
