apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "facets-notification-controller.fullname" . }}
  labels:
  {{- include "facets-notification-controller.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
