# Default values for iac-operator
# This is a YAML-formatted file
# Declare variables to be passed into your templates

replicaCount: 1

image:
  repository: facetscloud/iac-operator
  pullPolicy: IfNotPresent
  tag: "local-test-44"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# Operator configuration
operator:
  # Log level for the operator
  logLevel: info
  # Metrics port
  metricsPort: 8080
  # Health probe port
  healthPort: 8081
  # Leader election
  leaderElection:
    enabled: true
    resourceName: iac-operator-leader
    resourceNamespace: "" # Uses release namespace if empty

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations:
    eks.amazonaws.com/role-arn: <EKS_ROLE_ARN>
  # The name of the service account to use
  name: ""

rbac:
  # Specifies whether RBAC resources should be created
  create: true

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  fsGroup: 65532

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

service:
  type: ClusterIP
  port: 8080
  targetPort: metrics
  annotations: {}

# ServiceMonitor for Prometheus Operator
serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
  labels: {}
  annotations: {}

# Webhook configuration
webhook:
  enabled: true
  port: 9443
  certSecret: webhook-server-cert
  failurePolicy: Fail  # Fail or Ignore
  timeoutSeconds: 10
  service:
    type: ClusterIP
    annotations: {}

# API configuration for custom endpoints (approve, decline, status)
api:
  enabled: true
  service:
    type: ClusterIP  # ClusterIP, NodePort, LoadBalancer
    port: 8443
    nodePort: null  # Only used if type is NodePort
    annotations: {}
  ingress:
    enabled: false
    className: nginx
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: iac-operator.example.com
        paths:
          - path: /api/v1
            pathType: Prefix
    tls: []
    #  - secretName: iac-operator-tls
    #    hosts:
    #      - iac-operator.example.com

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# CRD installation
crds:
  # Install CRDs as part of the Helm chart
  install: true
  # Keep CRDs on chart uninstall
  keep: false

# Config for operator ConfigMap
config:
  # Additional environment variables
  env: {}
  # Additional volumes
  volumes: []
  # Additional volume mounts
  volumeMounts: []


